### ISSUE TITLE
I think we should use coolnameapi

### ISSUE THREAD

**Issue by aashutoshrathi** [yashLadha/cRaxYnM#1]
If internet => coolnamepi.
What say @yashLadha @mohitkyadav?

**Comment by mohitkyadav** [comment]
Sure, if @yashLadha agrees.

**Comment by yashLadha** [comment]
Don't have a problem with that, but my idea is to remove the network issue and do the on-device generation of strings. I think it can be called a flutter port of cool name :thinking:

**Comment by aashutoshrathi** [comment]
Offline seems legit, then I think we need a proper port, like in Cool Name API:
- I think we generated more type of strings
- Also, we need to add uncoolify (which is breaking as of now).

Right @mohitkyadav ?

**Comment by mohitkyadav** [comment]
@aashutoshrathi  yes, but uncoolify is breaking? since when?

**Comment by aashutoshrathi** [comment]
I mean there were few issues with some chars, which can go back to multiple alphabets
